// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interface.proto

/*
Package engine_client_proto is a generated protocol buffer package.

It is generated from these files:
	interface.proto

It has these top-level messages:
	AuthRequest
	Request
	Response
	IdentifiedResponse
*/
package engine_client_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	ClientId   []byte `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Credential []byte `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthRequest) GetClientId() []byte {
	if m != nil {
		return m.ClientId
	}
	return nil
}

func (m *AuthRequest) GetCredential() []byte {
	if m != nil {
		return m.Credential
	}
	return nil
}

type Request struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Response struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Error   []byte `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Response) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type IdentifiedResponse struct {
	Payload     []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	CommittedId []byte `protobuf:"bytes,2,opt,name=committedId,proto3" json:"committedId,omitempty"`
	Error       []byte `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *IdentifiedResponse) Reset()                    { *m = IdentifiedResponse{} }
func (m *IdentifiedResponse) String() string            { return proto.CompactTextString(m) }
func (*IdentifiedResponse) ProtoMessage()               {}
func (*IdentifiedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IdentifiedResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *IdentifiedResponse) GetCommittedId() []byte {
	if m != nil {
		return m.CommittedId
	}
	return nil
}

func (m *IdentifiedResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "engine_client_proto.AuthRequest")
	proto.RegisterType((*Request)(nil), "engine_client_proto.Request")
	proto.RegisterType((*Response)(nil), "engine_client_proto.Response")
	proto.RegisterType((*IdentifiedResponse)(nil), "engine_client_proto.IdentifiedResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RequestHandler service

type RequestHandlerClient interface {
	Invoke(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	IdentifiedInvoke(ctx context.Context, in *Request, opts ...grpc.CallOption) (*IdentifiedResponse, error)
	UserMan(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	SysMan(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Renew(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*Response, error)
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type requestHandlerClient struct {
	cc *grpc.ClientConn
}

func NewRequestHandlerClient(cc *grpc.ClientConn) RequestHandlerClient {
	return &requestHandlerClient{cc}
}

func (c *requestHandlerClient) Invoke(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/engine_client_proto.RequestHandler/Invoke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestHandlerClient) IdentifiedInvoke(ctx context.Context, in *Request, opts ...grpc.CallOption) (*IdentifiedResponse, error) {
	out := new(IdentifiedResponse)
	err := grpc.Invoke(ctx, "/engine_client_proto.RequestHandler/IdentifiedInvoke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestHandlerClient) UserMan(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/engine_client_proto.RequestHandler/UserMan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestHandlerClient) SysMan(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/engine_client_proto.RequestHandler/SysMan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestHandlerClient) Renew(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/engine_client_proto.RequestHandler/Renew", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestHandlerClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/engine_client_proto.RequestHandler/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestHandlerClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/engine_client_proto.RequestHandler/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RequestHandler service

type RequestHandlerServer interface {
	Invoke(context.Context, *Request) (*Response, error)
	IdentifiedInvoke(context.Context, *Request) (*IdentifiedResponse, error)
	UserMan(context.Context, *Request) (*Response, error)
	SysMan(context.Context, *Request) (*Response, error)
	Renew(context.Context, *Request) (*Response, error)
	Auth(context.Context, *AuthRequest) (*Response, error)
	Ping(context.Context, *Request) (*Response, error)
}

func RegisterRequestHandlerServer(s *grpc.Server, srv RequestHandlerServer) {
	s.RegisterService(&_RequestHandler_serviceDesc, srv)
}

func _RequestHandler_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestHandlerServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine_client_proto.RequestHandler/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestHandlerServer).Invoke(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestHandler_IdentifiedInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestHandlerServer).IdentifiedInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine_client_proto.RequestHandler/IdentifiedInvoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestHandlerServer).IdentifiedInvoke(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestHandler_UserMan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestHandlerServer).UserMan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine_client_proto.RequestHandler/UserMan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestHandlerServer).UserMan(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestHandler_SysMan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestHandlerServer).SysMan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine_client_proto.RequestHandler/SysMan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestHandlerServer).SysMan(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestHandler_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestHandlerServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine_client_proto.RequestHandler/Renew",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestHandlerServer).Renew(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestHandler_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestHandlerServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine_client_proto.RequestHandler/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestHandlerServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestHandler_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestHandlerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine_client_proto.RequestHandler/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestHandlerServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _RequestHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "engine_client_proto.RequestHandler",
	HandlerType: (*RequestHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _RequestHandler_Invoke_Handler,
		},
		{
			MethodName: "IdentifiedInvoke",
			Handler:    _RequestHandler_IdentifiedInvoke_Handler,
		},
		{
			MethodName: "UserMan",
			Handler:    _RequestHandler_UserMan_Handler,
		},
		{
			MethodName: "SysMan",
			Handler:    _RequestHandler_SysMan_Handler,
		},
		{
			MethodName: "Renew",
			Handler:    _RequestHandler_Renew_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _RequestHandler_Auth_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _RequestHandler_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interface.proto",
}

func init() { proto.RegisterFile("interface.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x5b, 0x6d, 0x93, 0x32, 0x15, 0x95, 0xd5, 0x43, 0x28, 0x2a, 0x61, 0x3d, 0xe8, 0x29,
	0x07, 0xbd, 0x79, 0xf3, 0xa0, 0xed, 0x1e, 0x04, 0x89, 0x78, 0xf2, 0x50, 0xd6, 0xec, 0xa4, 0x2e,
	0xa6, 0xbb, 0x71, 0xb3, 0x55, 0xfa, 0x79, 0xfc, 0xa2, 0x62, 0xfe, 0xd8, 0x80, 0x29, 0x16, 0xe2,
	0x71, 0xde, 0x1b, 0x7e, 0x6f, 0x66, 0x18, 0xd8, 0x93, 0xca, 0xa2, 0x89, 0x79, 0x84, 0x41, 0x6a,
	0xb4, 0xd5, 0xe4, 0x00, 0xd5, 0x4c, 0x2a, 0x9c, 0x46, 0x89, 0x44, 0x65, 0xa7, 0xb9, 0x48, 0x19,
	0x0c, 0xaf, 0x17, 0xf6, 0x25, 0xc4, 0xb7, 0x05, 0x66, 0x96, 0x8c, 0x60, 0x50, 0xd8, 0x4c, 0x78,
	0x5d, 0xbf, 0x7b, 0xbe, 0x13, 0xfe, 0xd4, 0xe4, 0x04, 0x20, 0x32, 0x28, 0x50, 0x59, 0xc9, 0x13,
	0x6f, 0x2b, 0x77, 0x6b, 0x0a, 0x3d, 0x05, 0xb7, 0xc2, 0x78, 0xe0, 0xa6, 0x7c, 0x99, 0x68, 0x5e,
	0x51, 0xaa, 0x92, 0x5e, 0xc1, 0x20, 0xc4, 0x2c, 0xd5, 0x2a, 0xc3, 0xf5, 0x5d, 0xe4, 0x10, 0xfa,
	0x68, 0x8c, 0x36, 0x65, 0x4a, 0x51, 0xd0, 0x18, 0x08, 0xcb, 0xc3, 0x62, 0x89, 0x62, 0x03, 0x8a,
	0x0f, 0xc3, 0x48, 0xcf, 0xe7, 0xd2, 0x5a, 0x14, 0x4c, 0x94, 0xac, 0xba, 0xb4, 0xca, 0xd9, 0xae,
	0xe5, 0x5c, 0x7c, 0xf6, 0x60, 0xb7, 0xdc, 0x64, 0xc2, 0x95, 0x48, 0xd0, 0x90, 0x31, 0x38, 0x4c,
	0xbd, 0xeb, 0x57, 0x24, 0x47, 0x41, 0xc3, 0x19, 0x83, 0xb2, 0x7d, 0x74, 0xbc, 0xc6, 0x2d, 0x66,
	0xa5, 0x1d, 0xf2, 0x04, 0xfb, 0xab, 0x1d, 0x36, 0x42, 0x9e, 0x35, 0xba, 0xbf, 0x0f, 0x41, 0x3b,
	0x64, 0x02, 0xee, 0x63, 0x86, 0xe6, 0x8e, 0xab, 0xb6, 0x63, 0x8e, 0xc1, 0x79, 0x58, 0x66, 0xff,
	0x00, 0xba, 0x85, 0x7e, 0x88, 0x0a, 0x3f, 0xda, 0x72, 0x18, 0xf4, 0xbe, 0xff, 0x94, 0xf8, 0x8d,
	0x8d, 0xb5, 0x17, 0xfe, 0x1b, 0x75, 0x03, 0xbd, 0x7b, 0xa9, 0x66, 0x2d, 0x27, 0x7a, 0x76, 0x72,
	0xe5, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x07, 0x79, 0x41, 0x06, 0x68, 0x03, 0x00, 0x00,
}
